version: 0.0
os: linux
files:
  - source: /ml-api
    destination: /home/ec2-user/ml-api
  - source: /recommendation-engine
    destination: /home/ec2-user/ml-api/py/recommendation-engine
hooks:
  AfterInstall:
    - location: /ml-api/devops/scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: /ml-api/devops/scripts/trainer.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /ml-api/devops/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /ml-api/devops/scripts/stop_server.sh
      timeout: 300
      runas: root