version: 0.0
os: linux
files:
  - source: /ml-api
    destination: /home/ec2-user/
  - source: /recommendation-engine
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: /devops/scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: /devops/scripts/getenvs.sh dev
      timeout: 300
      runas: root
    - location: /devops/scripts/trainer.sh
      timeout: 1800
      runas: root
  
  ApplicationStart:
    - location: /devops/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /devops/scripts/stop_server.sh
      timeout: 300
      runas: root