version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ml-api/
hooks:
  BeforeInstall:
    - location: /devops/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /devops/scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: /devops/scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /devops/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /devops/scripts/stop_server.sh
      timeout: 300
      runas: root