version: 0.0
os: linux
files:
  - source: /ml-api
    destination: /home/ec2-user/
  - source: /recommendation-engine
    destination: /home/ec2-user/ml-api/src/py
hooks:
  BeforeInstall:
    - location: /devops/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /devops/scripts/after_install.sh dev
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /devops/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /devops/scripts/stop_server.sh
      timeout: 300
      runas: root